Merge Experimental to Master
E-Edu/user pull request #23
Opened 2020-03-21 12:35 UTC by Ampferl

2020-03-21 12:57 UTC, felbinger commented on database/Database.py
> +    def __int__(self):
`__init__`?

2020-03-21 12:59 UTC, felbinger commented on database/Database.py
> +class AccountStatus(Enum):
import AccountStatus from `database/accountStatus.py`

2020-03-21 13:05 UTC, felbinger commented on src/main.py
> +    app.run(port=4450, threaded=True)
Change back to default port (`5000`) / remove port argument, please.

2020-03-21 13:09 UTC, JannikEmmerich requested changes
Please remove ` src/__pycache__/errorResponse.cpython-37.pyc`
Please remove `database/Database.py`

ORM (SQLAlchemy)?

2020-03-21 13:09 UTC, JannikEmmerich commented on README.md
> +```json
Please use `jsonc` instead of `json`

2020-03-21 13:09 UTC, JannikEmmerich commented on README.md
> +```json
Please use `jsonc` instead of `json`

2020-03-21 13:09 UTC, JannikEmmerich commented on README.md
> +```json
Please use `jsonc` instead of `json`

2020-03-21 13:09 UTC, JannikEmmerich commented on README.md
> +```json
Please use `jsonc` instead of `json`

2020-03-21 13:09 UTC, JannikEmmerich commented on README.md
> +```json
Please use `jsonc` instead of `json`

2020-03-21 13:09 UTC, JannikEmmerich commented on README.md
> +```json
Please use `jsonc` instead of `json`

2020-03-21 13:09 UTC, JannikEmmerich commented on docker-compose.yml
> +      MYSQL_RANDOM_ROOT_PASSWORD: test
Please use `true` instead of `test`

2020-03-21 13:09 UTC, JannikEmmerich commented on src/main.py
> +    app.run(port=4450, threaded=True)
Please use port `5000` and WSGI (Web Server Gateway Interface) `gunicorn`

2020-03-21 13:09 UTC, JannikEmmerich commented on src/user.py
> +    def __init__(self, email, password, first_name, last_name, status, created, role):
Please use an `UUID` to identify the user

2020-03-21 13:09 UTC, JannikEmmerich commented on database/database.py
> +        self.execute('CREATE TABLE IF NOT EXISTS User_Users (userId INT NOT NULL AUTO_INCREMENT, firstName VARCHAR(255), lastName VARCHAR(255), email VARCHAR(255), password VARCHAR(255), accountStatu
Please use an `UUID` as userId

2020-03-21 13:09 UTC, JannikEmmerich commented on database/database.py
> +        self.execute('INSERT INTO User_Users (firstName, lastName, email, password, accountStatus, role) VALUES (?, ?, ?, ?, ?, ?)', (firstName, lastName, email, hashedPassword, 0, role.value))
Please use an `UUID` as userId

2020-03-21 13:09 UTC, JannikEmmerich commented on src/main.py
> +    global content
Don't use global variables here

2020-03-21 14:20 UTC, MarcelCoding requested changes
Use `UUID` as `userId`!

2020-03-21 14:20 UTC, TheCataliasTNT2k requested changes

2020-03-21 14:20 UTC, TheCataliasTNT2k commented on docker-compose.yml
> +
include your microservice?

2020-03-21 21:23 UTC, TheCataliasTNT2k requested changes

2020-03-21 21:23 UTC, TheCataliasTNT2k commented on run.py
> +from service import app
gunicorn? https://github.com/E-Edu/user/pull/23#discussion_r395990191

2020-03-21 21:23 UTC, TheCataliasTNT2k commented on resources/setup.sql
> +    user_uuid VARCHAR(64) NOT NULL,
use foreign keys

2020-03-22 10:39 UTC, JannikEmmerich approved these changes

2020-03-22 10:39 UTC, merged